<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="IDCAMVERM01-WS" name="Scenario4_Test5" tests="2" failures="2" timestamp="15 Apr 2016 11:05:58 GMT" time="0.16" errors="0">
  <testcase name="verifyscore" time="0.085" classname="com.edifecs.breathe.qa.testcases.TestHealthRiskAssessmentSubmit">
    <failure type="java.lang.AssertionError" message="expected [3.0] but found [8.58]">
      <![CDATA[java.lang.AssertionError: expected [3.0] but found [8.58]
	at com.edifecs.breathe.qa.testcases.TestHealthRiskAssessmentSubmit.verifyscore(TestHealthRiskAssessmentSubmit.java:40)
	at com.edifecs.breathe.qa.testcases.RunTests.main(RunTests.java:102)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- verifyscore -->
  <testcase name="verifybuttonstatus" time="0.074" classname="com.edifecs.breathe.qa.testcases.TestHealthRiskAssessmentSubmit">
    <failure type="java.lang.AssertionError" message="Assessment completion status mismatched expected [Not Completed] but found [Completed 04.15.2016]">
      <![CDATA[java.lang.AssertionError: Assessment completion status mismatched expected [Not Completed] but found [Completed 04.15.2016]
	at com.edifecs.breathe.qa.testcases.TestHealthRiskAssessmentSubmit.verifybuttonstatus(TestHealthRiskAssessmentSubmit.java:65)
	at com.edifecs.breathe.qa.testcases.RunTests.main(RunTests.java:102)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- verifybuttonstatus -->
</testsuite> <!-- Scenario4_Test5 -->
